### ISSUE TITLE
Add more options

### ISSUE THREAD

**Issue by headyj** [23technologies/xp-fn-rndstr#3]
Hello,

It would be very nice if we could have more options except the length, like the ones you have with terraform random_password: https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/password.html

Is that something you plan to add?

**Comment by j2L4e** [comment]
Actually no. We switched to [function-go-templating](https://github.com/crossplane-contrib/function-go-templating), which enables us to use sprig's `randAlphaNum` function for our use-case. So this repo is practically dead and will be archived. Feel free to fork!
